### ISSUE TITLE
GD crash log

### ISSUE THREAD

**Issue by ItzN1N9** [geode-sdk/example-mod#7] opened 2024-05-09 21:31 UTC
2024-05-10T05:07:22.522112367 [E/AndroidRuntime]: FATAL EXCEPTION: GLThread 4292
Process: com.geode.launcher, PID: 3897
java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1223)
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1214)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1064)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
2024-05-10T05:07:28.684447137 [E/AndroidRuntime]: FATAL EXCEPTION: GLThread 4285
Process: com.geode.launcher, PID: 4341
java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1223)
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1214)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1064)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
2024-05-10T05:14:36.621140009 [E/]: nFreeSize: 31137210368
2024-05-10T05:14:36.624821470 [E/]: nFreeSize: 31137210368
2024-05-10T05:14:37.501174239 [E/]: nFreeSize: 31137148928
2024-05-10T05:14:37.522772855 [E/]: nFreeSize: 31137140736
2024-05-10T05:14:38.140694701 [E/]: nFreeSize: 31137148928
2024-05-10T05:14:38.144680163 [E/]: nFreeSize: 31137140736
2024-05-10T05:15:23.984701088 [E/]: nFreeSize: 31147880448
2024-05-10T05:15:24.551595627 [E/AndroidRuntime]: FATAL EXCEPTION: GLThread 4413
Process: com.geode.launcher, PID: 8988
java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1223)
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1214)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1064)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
2024-05-10T05:15:28.882836319 [E/]: nFreeSize: 31136927744
2024-05-10T05:15:28.886164858 [E/]: nFreeSize: 31136927744
2024-05-10T05:15:36.529576858 [E/]: nFreeSize: 31136948224

**Comment by qimiko** [comment] 2024-05-10 01:58
you're in the really wrong place. what the heck

anyways, duplicate of geode-sdk/android-launcher#25 which will be fixed in the next release :slightly_smiling_face:

**Closed as not planned by qimiko** 2024-05-10 01:58 UTC
